<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array(
	'Cannot create directory {dir}' => 'Невозможно создать папку {dir}',
	'Delete image' => 'Удалить изображение',
	'Current file' => 'Существующий файл',
	'Download original' => 'Скачать оригинал',
	'Image path for attribute "{attr}" must be specified.' => 'Должен быть задан путь к изображению для атрибута "{attr}".',
	'Unable to write in file {file} when processing attribute {attribute}' => 'Невозможно записать файл "{file}" во время обработки атрибута "{attribute}"',
	'Unknown transformation {transform} in {class}' => 'Неизвестное преобразование {transform} в классе {class}',
	'View full size image' => 'Смотреть полноразмерной изображение',
	'driver must be GD or ImageMagick' => 'Драйвер должен быть либо "GD" либо "ImageMagick"',
	'image directory unwritable' => 'Невозможно записать изображение в папку',
	'image driver must be implement Image_Driver class' => 'Драйвер должен быть наследником класса Image_Driver',
	'image file not found' => 'Файл изображения не найден',
	'image file unreadable' => 'Невозможно прочесть файл изображения',
	'image gd requires v2' => 'Требуется GD v.2',
	'image getimagesize missing' => 'Отсутствует функция getimagesize',
	'image imagemagick not_found' => 'Не найден imagemagick',
	'image invalid dimensions' => 'Неправильный параметр dimensions',
	'image invalid flip' => 'Неправильный параметр flip',
	'image invalid height' => 'Неправильная высота',
	'image invalid horizontal align value' => 'Неправильное значение горизонтального выравнивания',
	'image invalid horizontal margin' => 'Неправильный горизонтальный отступ',
	'image invalid left' => 'Неправильный параметр left',
	'image invalid master' => 'Неправильный параметр master',
	'image invalid top' => 'Неправильный параметр top',
	'image invalid vertical align value' => 'Неправильное значение вертикального выравнивания',
	'image invalid vertical margin' => 'Неправильный вертикальный отступ',
	'image invalid width' => 'Неправильная ширина',
	'image type not allowed' => 'Недозволенный тип изображения',
	'image unsupported method' => 'Неподрживаемый тип изображения',
	'invalid property' => 'Неправильное свойство',
	'n/a' => 'Н/Д',
	'watermark file not exists or not image' => 'Не найден файл изображения водяного знака или файл не является картинкой',
	'File loaded is not image.' => 'Загруженный файл не является изображением.',
);
